export const metadata = {
  title: 'Terms of Service — RealmForge',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground px-6 py-16">
      <div className="max-w-2xl mx-auto space-y-8">
        <div>
          <h1 className="text-3xl font-bold text-amber-highlight mb-2">Terms of Service</h1>
          <p className="text-xs text-foreground/50">Last updated: 2026-05-15</p>
        </div>

        <Section title="Acceptance">
          By creating an account or using RealmForge, you agree to these Terms. If you do not agree,
          please do not use the service.
        </Section>

        <Section title="What RealmForge is">
          RealmForge is an AI-assisted Dungeons &amp; Dragons platform. The AI Dungeon Master is
          generated by large language models and may occasionally produce inaccurate, inconsistent, or
          unexpected content. It is not a substitute for a human Dungeon Master and should be treated
          as entertainment.
        </Section>

        <Section title="Acceptable use">
          You agree not to:
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Use the platform to generate illegal content or content that violates Anthropic&apos;s or Groq&apos;s usage policies.</li>
            <li>Attempt to reverse-engineer, abuse, or circumvent the rate limits or safety filters.</li>
            <li>Share your account credentials or use the platform on behalf of others without their consent.</li>
            <li>Use the service for any commercial purpose without written permission.</li>
          </ul>
        </Section>

        <Section title="AI-generated content">
          Campaign text, narration, and suggestions are generated by AI. We do not review AI output
          in real time. If you encounter content you believe violates these terms, use the flag button
          in the app or contact us directly.
        </Section>

        <Section title="Content you create">
          You retain ownership of campaign names, character backstories, and other creative content
          you author. By using the platform, you grant us a limited licence to store and process that
          content to provide the service.
        </Section>

        <Section title="Availability">
          We aim for high availability but make no uptime guarantees. The service may be interrupted
          for maintenance, or discontinued with 30 days&apos; notice.
        </Section>

        <Section title="Limitation of liability">
          RealmForge is provided &ldquo;as is&rdquo;. To the maximum extent permitted by law, we are not liable
          for any indirect, incidental, or consequential damages arising from your use of the service.
        </Section>

        <Section title="Changes">
          We may update these Terms at any time. Continued use of the service after an update
          constitutes acceptance of the new Terms.
        </Section>

        <Section title="Contact">
          Questions? Email{' '}
          <a href="mailto:shubham.mohta.2995@gmail.com" className="text-amber-highlight underline">
            shubham.mohta.2995@gmail.com
          </a>.
        </Section>
      </div>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="text-sm text-foreground/70 leading-relaxed">{children}</div>
    </section>
  )
}
